name: Greeting

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday
  DOCKER_IMAGE : ${{ secrets.IMAGE_NAME }}
  DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello"
        run: echo "$DOCKER_IMAGE $DOCKER_USERNAME Today is $First_Name"
        env:
          First_Name: Mona
